recipe: default.v1
language: en

pipeline:
- name: SingleStepLLMCommandGenerator
  llm:
    model_group: openai-gpt-4o
  flow_retrieval:
    active: false

policies:
- name: FlowPolicy


assistant_id: cue-clinic-appointment-system
