name: Test Rasa Environment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.0'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install 'uv[pyproject]'
          uv pip install rasa-pro --system
          if [ -f requirements.txt ]; then uv pip install -r requirements.txt --system; fi
      - name: Test Rasa
        run: |
          rasa --version
          rasa train 