name: Test Rasa Environment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.0'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install rasa==3.12.1 rasa-sdk==3.12.0
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Test Rasa
        run: |
          rasa --version
          rasa train 